spring: 
  redis:
    host: 192.168.101.65
    port: 6379
    password: redis
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0
    timeout: 10000
    redisson:
    #实现分布式锁
      #配置文件目录
      config: classpath:singleServerConfig.yaml
      # config: classpath:clusterServersConfig.yaml
