server:
  servlet:
    context-path: /auth
  port: 9527
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.101.65:3306/zrc_users?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: mysql

weixin:
  appid: wx17655f8047b85150
  secret: 68918d65287802a19b1905cbda7eaa93