spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.101.65:3306/zrc_content?serverTimezone=UTC&userUnicode=true&useSSL=false&
        username: root
        password: mysql

xxl:
  job:
    admin: 
      addresses: http://192.168.101.65:8088/xxl-job-admin
    executor:
      appname: content-service-coursepublish
      address: 
      ip: 
      port: 8010
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken: default_token