spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.101.65:3306/zrc_orders?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: mysql

xxl:
  job:
    admin: 
      addresses: http://192.168.101.65:8088/xxl-job-admin
    executor:
      appname: payresultnotify-job
      address: 
      ip: 
      port: 8989
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken: default_token



pay:
  qrcodeurl: http://192.168.101.1/api/orders/requestpay?payNo=%s
  alipay:
    APP_ID: 
    APP_PRIVATE KEY: 
    APP_PUBLIC KEY: 
